# Generated by Django 3.2.9 on 2021-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_enterprise',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
