# Generated by Django 3.2.9 on 2021-12-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_user_name_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nif_stat',
            field=models.CharField(default=' ', max_length=200, verbose_name='Nif-Stat'),
        ),
    ]
