# Generated by Django 3.2.9 on 2021-12-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20211207_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='Est un recruteur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='Est un formateur'),
        ),
    ]
