# Generated by Django 3.2.9 on 2021-12-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaljob_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_info',
            name='description',
            field=models.TextField(default='', verbose_name='Description on the job'),
        ),
    ]
