# Generated by Django 3.2.9 on 2021-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaljob_activity', '0002_recruitment_info_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_photo', models.ImageField(upload_to='portaljob_activity')),
            ],
        ),
    ]
