# Generated by Django 3.2.9 on 2021-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaljob_activity', '0003_administration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='this is the name')),
            ],
        ),
        migrations.AlterField(
            model_name='recruitment_info',
            name='pub_date',
            field=models.DateField(default='', verbose_name='date de publication'),
        ),
    ]
